
filewatcher_sleep_time: 15
data_export_base_dir: /home/paul/dev/eth_data_analyze_home_dir/temp_storage
storage_type: filesystem
log_level: DEBUG
cron_seconds_to_sleep: 15
include_hash_file: true

max_workers: 5
dask:
  scheduler_url: 127.0.0.1:8786
  n_workers: 3
  threads_per_worker: 1
  memory_limit: 20GB
  engine: 'pyarrow'
  compression: 'snappy'
  group_divisions_by: 200
  temp_directory: /home/paul/dev/eth_data_analyze_home_dir/dask/temp

data_organizer:
  enabled: false
  csv_export_location: /mnt/crypto/export

data_elements:
  list:
  - element_name: blocknumber_to_transactions
    type: file
    file_pattern: 'block_number_with_transactions_file*'
    data_export_relative_directory: blocknumber_to_transactions
    columns:
    - name: block_number
      type: uint32
    - name: transaction_number

data_elements_to_extract:
  enabled: false
  list:
    - element_name_to_extract: blocknumber_to_transactions
      enabled: true

data_elements_to_append:
  enabled: false
  list:
  - element_name: blocknumber_to_transactions_append
    element_name_to_append: blocknumber_to_transactions
    data_export_relative_directory: blocknumber_to_transactions_append
    index:
        name: block_number
        type: uint32
    enabled: true

pre_processing_long_term_data_storage:
  enabled: true
  list:
    - element_name: blocknumber_to_transactions_long_term_storage_partitioned_by_block_number
      element_name_to_store: blocknumber_to_transactions_append
      data_export_relative_directory: long_term_storage/pre_processing/blocknumber_to_transactions/partitioned_by_block_number
      index:
        name: block_number
        type: uint32
      columns:
      - name: transaction_number
      npartitions: 1000
      export_to_csv: true
      enabled: true

data_elements_to_analyze:
  enabled: false
  list:
  - enabled: true
    element_name: analyze_epcm_messages_aggregations
    element_name_to_analyze: epcm_messages_long_term_storage_partitioned_by_device_irn
    index:
      name: DEVICE_IRN
      type: uint64
    data_export_relative_directory: analyze_epcm_messages_aggregations
    timezone_from: UTC
    filter_date_greater_then: 2020-01-01
    aggregations:
  - enabled: true
    element_name: analyze_epcm_messages_long_term_storage_partitioned_by_device_irn
    element_name_to_analyze: consumption_long_term_storage_partitioned_by_device_irn
    index:
      name: DEVICE_IRN
      type: uint64
    data_export_relative_directory: analyze
    timezone_from: UTC
    filter_date_greater_then: 2020-01-01
    consumption:
      total_kwh_delivered_object_number: 3760195585
      element_name_long_term_storage: consumption_long_term_storage_partitioned_by_device_irn
      create_stitched: true
      create_interval: true
      reports:
        break_consumption_into_intervals: true
        interval: 'H'
  - enabled: true
    element_name: analyze_interval_data_epcm_messages_long_term_storage_partitioned_by_device_irn
    element_name_to_analyze: interval_data_long_term_storage_partitioned_by_device_irn
    index:
      name: DEVICE_IRN
      type: uint64
    data_export_relative_directory: analyze
    timezone_from: UTC
    filter_date_greater_then: 2020-01-01
    interval:
      object_number: 3760212050
      start_date: 2000-04-05T00:00:00-0400
      end_date: 2030-04-06T00:00:00-0400
      interval_in_minutes: 15

post_processing_long_term_data_storage:
  list:
    - element_name: long_term_storage_consumption_stitched
      data_export_relative_directory: long_term_storage/post_processing/consumption_stitched
      index:
        name: DEVICE_IRN
        type: uint64
      unique_columns: [DEVICE_IRN, START_DATE, END_DATE]
      columns:
      - name: DEVICE_IRN
        type: uint32
      - name: START_DATE
      - name: END_DATE
      - name: CONSUMPTION_START
      - name: CONSUMPTION_END
      - name: CONSUMPTION_KWH
      - name: SEQNUM_START
        type: uint64
      - name: SEQNUM_END
        type: uint64
      repartition: true
      set_index: true
      npartitions: 5000
    - element_name: long_term_storage_consumption_as_interval
      data_export_relative_directory: long_term_storage/post_processing/consumption_as_interval
      index:
        name: DEVICE_IRN
        type: uint64
      unique_columns: [DEVICE_IRN, INTERVAL]
      columns:
      - name: DEVICE_IRN
        type: uint32
      - name: INTERVAL
      - name: VALUE
        type: float64
      - name: SEQNUM_START
        type: uint64
      - name: SEQNUM_END
        type: uint64
      repartition: true
      set_index: true
      npartitions: 5000
    - element_name: long_term_storage_interval_data
      data_export_relative_directory: long_term_storage/post_processing/interval_data
      index:
        name: DEVICE_IRN
        type: uint64
      unique_columns: [DEVICE_IRN, READ_TIME]
      columns:
      - name: DEVICE_IRN
        type: uint32
      - name: READ_TIME
      - name: WAN_ENDPOINT_IRN
        type: uint32
      - name: VALUE
        type: float64
      - name: SEQNUM
        type: uint64
      - name: GENERATED_BECAUSE_OF_GAP
      repartition: true
      set_index: true
      npartitions: 5000

data_elements_to_copy:
  enabled: false
  list:
    - name: copy_alphameter
      data_element_name_to_copy: alphameter
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: false

data_elements_to_export_to_csv:
  enabled: true
  list:
    - name: to_csv_blocknumber_to_transactions_long_term_storage_partitioned_by_block_number
      data_element_name_to_export_to_csv: blocknumber_to_transactions_long_term_storage_partitioned_by_block_number
      enabled: true


