mas_home: d:/ee
filewatcher_sleep_time: 15
data_export_base_dir: G:/data_crunch_storage/temp_storage
storage_type: filesystem
log_level: DEBUG
cron_seconds_to_sleep: 15
include_hash_file: true
dir_webgui_xml: d:/dev

max_workers: 5
dask:
  scheduler_url: 127.0.0.1:8786
  n_workers: 3
  threads_per_worker: 1
  memory_limit: 40GB
  engine: 'pyarrow'
  compression: 'snappy'
  group_divisions_by: 200

debug:
  stop_processing_at_device_irn_equal_to: -1
  only_analyze_devices_in_range:
    start_device_irn: -1
    end_device_irn: -1

on_prem:
  enabled: true
  csv_export_location: d:/2/factsbi
  backup_incrementatal:
    enabled: false
    data_backup_dir: g:/data_crunch_storage/backup
  drill_common_folder: g:/data_crunch_storage/drill
  dask_temp_directory: g:/data_crunch_storage/dask_temp

azure:
  enabled: false
  storage_account_name: bistore2
  container_name: raw
  key: 0

data_elements:
  list:
  - element_name: alphameter
    type: file
    file_pattern: '*alphameter.csv'
    data_export_relative_directory: alphameter
    allways_get_all_rows: true
    order_by: alphameter.irn
    columns:
    - name: IRN
      type: uint32
    - name: NAME
    - name: SERIALNO
    - name: METERSTYLE_IRN
      type: uint32
    - name: PHONE
    - name: INSTALL_DATE
      is_date: true
    - name: REMOVAL_DATE
      is_date: true
    - name: ROUTE_ID
    - name: LATITUDE
    - name: LONGITUDE
  - element_name: alarms
    type: file
    file_pattern: '*auto_gen_alarms.csv'
    data_export_relative_directory: alarms
    allways_get_all_rows: true
    order_by: seqnum
    columns:
      - name: SEQNUM
        type: uint64
      - name: ELEMENT_IRN
        type: uint32
      - name: NAME
      - name: ACCOUNT_ID
      - name: ACCOUNT_NAME
      - name: SERIALNO
      - name: INSTALL_DATE
        is_date: true
      - name: REMOVAL_DATE
        is_date: true
      - name: ISCOLLECTOR
      - name: IS_DISCONNECTABLE
      - name: TYPE
      - name: METERSTYLE_IRN
        type: uint32
      - name: METER_TYPE
      - name: EVENT_ID
      - name: EVENT_NAME
      - name: EVENT_CATEGORY
      - name: VALUE
      - name: DETECTIONTIME
      - name: STARTTIME
      - name: ENDTIME
      - name: ACKNOWLEDGED
      - name: ACKNOWLEDGED_DATE
      - name: ACKNOWLEDGED_USER
      - name: EVENTINFORMATION
      - name: SEVERITY_CODE
      - name: SEVERITY

  - element_name: events
    type: file
    file_pattern: '*auto_gen_events.csv'
    data_export_relative_directory: events
    allways_get_all_rows: true
    order_by: seqnum
    columns:
      - name: SEQNUM
      - name: ELEMENT_IRN
      - name: NAME
      - name: ACCOUNT_ID
      - name: ACCOUNT_NAME
      - name: SERIALNO
      - name: INSTALL_DATE
        is_date: true
      - name: REMOVAL_DATE
        is_date: true
      - name: ISCOLLECTOR
      - name: IS_DISCONNECTABLE
      - name: TYPE
      - name: METERSTYLE_IRN
      - name: METER_TYPE
      - name: EVENT_ID
      - name: EVENT_NAME
      - name: EVENT_CATEGORY
      - name: VALUE
      - name: DETECTIONTIME
      - name: STARTTIME
      - name: ENDTIME
      - name: ACKNOWLEDGED
      - name: ACKNOWLEDGED_DATE
      - name: ACKNOWLEDGED_USER
      - name: EVENTINFORMATION
      - name: SEVERITY_CODE
      - name: SEVERITY
  - element_name: hops
    type: file
    file_pattern: '*auto_gen_hops.csv'
    data_export_relative_directory: hops
    allways_get_all_rows: true
    columns:
      - name: IRN
        type: uint32
      - name: LVL
      - name: REPEATER_NAME
      - name: NAME
      - name: LAST_REGISTER_READ
        is_date: true
      - name: LAST_INTERVAL_READ
        is_date: true
      - name: LAN_PERF_PERCENT
      - name: NUM_DESCENDANTS
      - name: LATITUDE
      - name: LONGITUDE
      - name: HOP_KM
      - name: FIRMWARE
  - element_name: meterstyle
    type: file
    file_pattern: '*auto_gen_meterstyle.csv'
    data_export_relative_directory: meterstyle
    allways_get_all_rows: true
    columns:
      - name: IRN
        type: uint32
      - name: NAME
      - name: UI_NAME

  - element_name: object_numbers
    type: file
    file_pattern: '*object_numbers.csv'
    data_export_relative_directory: object_numbers
    csv_separator: '|' # If we do not always get all the rows every time we need more metadata. This will be used to construct the sql query
    allways_get_all_rows: true
    columns:
    - name: OBJECT_NUMBER
      type: uint32
    - name: PERIOD
    - name: PERIOD_TEXT
    - name: TYPE
    - name: TYPE_TEXT
    - name: SUBTYPE
    - name: SUBTYPE_TEXT
    - name: TIER
    - name: TIER_TEXT
    - name: UOM_CODE
    - name: UOM_TEXT
    - name: DIRECTION_TEXT
    - name: QUADRANT_TEXT
  - element_name: epcm_messages
    type: file
    file_pattern: '*epcm_messages.csv'
    data_export_relative_directory: epcm_messages
    orderby:
      - DEVICE_IRN
      - OBJECT_NUMBER
      - READ_TIME
      - DATE_TIME_UTC
    columns:
      - name: DATE_TIME_UTC
        is_date: true
        timezone:
          from: UTC
          to: AST
      - name: READ_TIME
        is_date: true
        timezone:
          from: UTC
          to: AST
      - name: DEVICE_IRN
        type: uint32
      - name: WAN_ENDPOINT_IRN
        type: uint32
      - name: OBJECT_NUMBER
        type: uint32
      - name: VALUE
        type: float64
      - name: SEQNUM
        type: uint64
  - element_name: epcm_messages_incremental
    type: dir
    file_pattern: 'epcm_messages_incremental_*.csv'
    data_export_relative_directory: epcm_messages_incremental
    date_format: '%m/%d/%Y %H:%M:%S'
    orderby:
      - DEVICE_IRN
      - OBJECT_NUMBER
      - READ_TIME
      - DATE_TIME_UTC
    allways_get_all_rows: true
    columns:
      - name: DATE_TIME_UTC
        is_date: true
      - name: READ_TIME
        is_date: true
      - name: DEVICE_IRN
        type: uint32
      - name: WAN_ENDPOINT_IRN
        type: uint32
      - name: OBJECT_NUMBER
        type: uint32
      - name: VALUE
        type: float64
      - name: SEQNUM
        type: uint64
  - element_name: consumption_out_of_order_logger
    description: 'Log when consumption reads come in out of order'
    type: parquet
    data_export_relative_directory: consumption_logger
    columns:
      - name: CURRENT_CONSUMPTION_SEQNUM
      - name: PREVIOUS_CONSUMPTION_SEQNUM


data_elements_to_extract:
  enabled: false
  list:
    - element_name_to_extract: alphameter
      enabled: true
    - element_name_to_extract: object_numbers
      enabled: true
    - element_name_to_extract: epcm_messages_incremental
      enabled: true
    - element_name_to_extract: alarms
      enabled: false
    - element_name_to_extract: events
      enabled: false
    - element_name_to_extract: hops
      enabled: false
    - element_name_to_extract: meterstyle
      enabled: true

data_elements_to_append:
  enabled: true
  list:
  - element_name: epcm_messages_incremental_file_append
    element_name_to_append: epcm_messages_incremental
    data_export_relative_directory: epcm_messages_incremental_file_append
    enabled: true

pre_processing_long_term_data_storage:
  enabled: false
  list:
    - element_name: epcm_messages_long_term_storage_partitioned_by_device_irn
      element_name_to_store: epcm_messages_incremental_file_append
      data_export_relative_directory: long_term_storage/pre_processing/epcm_messages/partitioned_by_device_irn
      index:
        name: DEVICE_IRN
        type: uint64
      columns:
      - name: DATE_TIME_UTC
        is_date: true
      - name: READ_TIME
        is_date: true
      - name: DEVICE_IRN
        type: uint32
      - name: WAN_ENDPOINT_IRN
        type: uint32
      - name: OBJECT_NUMBER
        type: uint32
      - name: VALUE
        type: float64
      - name: SEQNUM
        type: uint64
      npartitions: 5000
      enabled: true
    - element_name: epcm_messages_long_term_storage_partitioned_by_read_time
      element_name_to_store: epcm_messages_long_term_storage_partitioned_by_device_irn
      data_export_relative_directory: long_term_storage/pre_processing/epcm_messages/partitioned_by_read_time
      index:
        name: READ_TIME
        type: datetime64
      columns:
        - name: DATE_TIME_UTC
          is_date: true
        - name: READ_TIME
          is_date: true
        - name: DEVICE_IRN
          type: uint32
        - name: WAN_ENDPOINT_IRN
          type: uint32
        - name: OBJECT_NUMBER
          type: uint32
        - name: VALUE
          type: float64
        - name: SEQNUM
          type: uint64
      npartitions: 5000
      enabled: true
    - element_name: consumption_long_term_storage_partitioned_by_device_irn
      element_name_to_store: epcm_messages_long_term_storage_partitioned_by_device_irn
      data_export_relative_directory: long_term_storage/pre_processing/consumption/partitioned_by_device_irn
      index:
        name: DEVICE_IRN
        type: uint64
      filter: OBJECT_NUMBER==3760195585
      filter_date_greater_then: 2020-01-01
      drop_duplicates:
        subset:
        - DEVICE_IRN
        - READ_TIME
      columns:
      - name: DATE_TIME_UTC
        is_date: true
      - name: READ_TIME
        is_date: true
      - name: DEVICE_IRN
        type: uint32
      - name: WAN_ENDPOINT_IRN
        type: uint32
      - name: OBJECT_NUMBER
        type: uint32
      - name: VALUE
      - name: SEQNUM
        type: uint64
      npartitions: 2000
      enabled: true
    - element_name: voltage_long_term_storage_partitioned_by_device_irn
      element_name_to_store: epcm_messages_long_term_storage_partitioned_by_device_irn
      data_export_relative_directory: long_term_storage/pre_processing/voltage/partitioned_by_device_irn
      index:
        name: DEVICE_IRN
        type: uint64
      filter: OBJECT_NUMBER==262286
      filter_date_greater_then: 2020-01-01
      drop_duplicates:
        subset:
          - DEVICE_IRN
          - READ_TIME
      columns:
        - name: DATE_TIME_UTC
          is_date: true
        - name: READ_TIME
          is_date: true
        - name: DEVICE_IRN
          type: uint32
        - name: WAN_ENDPOINT_IRN
          type: uint32
        - name: OBJECT_NUMBER
          type: uint32
        - name: VALUE
        - name: SEQNUM
          type: uint64
      npartitions: 5000
      enabled: true
    - element_name: interval_data_long_term_storage_partitioned_by_device_irn
      element_name_to_store: epcm_messages_long_term_storage_partitioned_by_device_irn
      data_export_relative_directory: long_term_storage/pre_processing/intervaldata/partitioned_by_device_irn
      index:
        name: DEVICE_IRN
        type: uint64
      filter: OBJECT_NUMBER==3760212050
      filter_date_greater_then: 2020-01-01
      drop_duplicates:
        subset:
        - DEVICE_IRN
        - READ_TIME
      columns:
      - name: DATE_TIME_UTC
        is_date: true
      - name: READ_TIME
        is_date: true
      - name: DEVICE_IRN
        type: uint32
      - name: WAN_ENDPOINT_IRN
        type: uint32
      - name: OBJECT_NUMBER
        type: uint32
      - name: VALUE
      - name: SEQNUM
        type: uint64
      npartitions: 5000
      enabled: true

data_elements_to_analyze:
  enabled: true
  list:
  - enabled: true
    element_name: analyze_epcm_messages_aggregations
    element_name_to_analyze: epcm_messages_long_term_storage_partitioned_by_device_irn
    index:
      name: DEVICE_IRN
      type: uint64
    data_export_relative_directory: analyze_epcm_messages_aggregations
    timezone_from: UTC
    filter_date_greater_then: 2020-01-01
    aggregations:
  - enabled: true
    element_name: analyze_epcm_messages_long_term_storage_partitioned_by_device_irn
    element_name_to_analyze: consumption_long_term_storage_partitioned_by_device_irn
    index:
      name: DEVICE_IRN
      type: uint64
    data_export_relative_directory: analyze
    timezone_from: UTC
    filter_date_greater_then: 2020-01-01
    consumption:
      total_kwh_delivered_object_number: 3760195585
      element_name_long_term_storage: consumption_long_term_storage_partitioned_by_device_irn
      create_stitched: true
      create_interval: true
      reports:
        break_consumption_into_intervals: true
        interval: 'H'
  - enabled: true
    element_name: analyze_interval_data_epcm_messages_long_term_storage_partitioned_by_device_irn
    element_name_to_analyze: interval_data_long_term_storage_partitioned_by_device_irn
    index:
      name: DEVICE_IRN
      type: uint64
    data_export_relative_directory: analyze
    timezone_from: UTC
    filter_date_greater_then: 2020-01-01
    interval:
      object_number: 3760212050
      start_date: 2000-04-05T00:00:00-0400
      end_date: 2030-04-06T00:00:00-0400
      interval_in_minutes: 15

post_processing_long_term_data_storage:
  list:
    - element_name: long_term_storage_consumption_stitched
      data_export_relative_directory: long_term_storage/post_processing/consumption_stitched
      index:
        name: DEVICE_IRN
        type: uint64
      unique_columns: [DEVICE_IRN, START_DATE, END_DATE]
      columns:
      - name: DEVICE_IRN
        type: uint32
      - name: START_DATE
      - name: END_DATE
      - name: CONSUMPTION_START
      - name: CONSUMPTION_END
      - name: CONSUMPTION_KWH
      - name: SEQNUM_START
        type: uint64
      - name: SEQNUM_END
        type: uint64
      repartition: true
      set_index: true
      npartitions: 5000
    - element_name: long_term_storage_consumption_as_interval
      data_export_relative_directory: long_term_storage/post_processing/consumption_as_interval
      index:
        name: DEVICE_IRN
        type: uint64
      unique_columns: [DEVICE_IRN, INTERVAL]
      columns:
      - name: DEVICE_IRN
        type: uint32
      - name: INTERVAL
      - name: VALUE
        type: float64
      - name: SEQNUM_START
        type: uint64
      - name: SEQNUM_END
        type: uint64
      repartition: true
      set_index: true
      npartitions: 5000
    - element_name: long_term_storage_interval_data
      data_export_relative_directory: long_term_storage/post_processing/interval_data
      index:
        name: DEVICE_IRN
        type: uint64
      unique_columns: [DEVICE_IRN, READ_TIME]
      columns:
      - name: DEVICE_IRN
        type: uint32
      - name: READ_TIME
      - name: WAN_ENDPOINT_IRN
        type: uint32
      - name: VALUE
        type: float64
      - name: SEQNUM
        type: uint64
      - name: GENERATED_BECAUSE_OF_GAP
      repartition: true
      set_index: true
      npartitions: 5000

data_elements_to_copy:
  enabled: true
  list:
    - name: copy_alphameter
      data_element_name_to_copy: alphameter
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: false
    - name: copy_object_numbers
      data_element_name_to_copy: object_numbers
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_alarms
      data_element_name_to_copy: alarms
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_events
      data_element_name_to_copy: events
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_hops
      data_element_name_to_copy: hops
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_meterstyle
      data_element_name_to_copy: meterstyle
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_consumption_long_term_storage_partitioned_by_device_irn
      data_element_name_to_copy: consumption_long_term_storage_partitioned_by_device_irn
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_long_term_storage_consumption_stitched
      data_element_name_to_copy: long_term_storage_consumption_stitched
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_long_term_storage_consumption_as_interval
      data_element_name_to_copy: long_term_storage_consumption_as_interval
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_analyze_epcm_messages_aggregations
      data_element_name_to_copy: analyze_epcm_messages_aggregations
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_long_term_storage_interval_data
      data_element_name_to_copy: long_term_storage_interval_data
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true
    - name: copy_voltage_long_term_storage_partitioned_by_device_irn
      data_element_name_to_copy: voltage_long_term_storage_partitioned_by_device_irn
      name_of_onprem_parameter_with_directory_location: drill_common_folder
      enabled: true



db:
  fetchsize: 10000
  commuser_info:
    url: connexo112fresh.eastus2.cloudapp.azure.com
    port: '1521'
    sid: amr
    user:
    password:
